services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env 